Dev
SJTU-jCourse/jcourse_api pull request #11
Opened 2022-10-31 18:47 UTC by chshzhe

2022-10-31 18:52 UTC, chshzhe commented
Oh, Jesus! Conflicted!

2022-11-01 05:53 UTC, dujiajun commented on jcourse_api/views.py
> +    viewsets.ReadOnlyModelViewSet
留 ReadOnly 就行

2022-11-01 05:53 UTC, dujiajun commented on jcourse_api/views.py
> +    pagination_class = None
需要分页的吧

2022-11-01 05:53 UTC, dujiajun commented on jcourse_api/views.py
> +        except (Action.DoesNotExist, Notification.DoesNotExist):
这里和Action有啥关系？忘记删了？

2022-11-01 05:53 UTC, dujiajun commented on jcourse_api/views.py
> +    #     return Response(data)
注释删了呗

2022-11-01 05:53 UTC, dujiajun commented on jcourse_api/models.py
> +    notification = GenericRelation(Notification)
这几个还没实现的功能，这次提交就先不改

2022-11-01 05:53 UTC, dujiajun commented on jcourse_api/models.py
> +            type=7,
用常量，不要用魔法数字，不然看不懂

2022-11-01 07:26 UTC, dujiajun requested changes

2022-11-01 07:26 UTC, dujiajun commented on jcourse_api/views.py
> +                        status=status.HTTP_200_OK)
检查一下 notification 是否是自己的，不然可以把别人的已读了

2022-11-01 07:26 UTC, dujiajun commented on jcourse_api/views.py
> +from rest_framework.pagination import PageNumberPagination
不需要的import清理掉

2022-11-01 08:05 UTC, dujiajun requested changes

2022-11-01 08:05 UTC, dujiajun commented on jcourse_api/admin.py
> +from django.core.mail import send_mail
这个也没用了吧

2022-11-01 08:30 UTC, chshzhe commented
fixed

2022-11-01 10:06 UTC, dujiajun approved these changes

2022-11-02 06:43 UTC, dujiajun approved these changes

2022-11-02 06:43 UTC, merged