feat: email login
SJTU-jCourse/jcourse_api pull request #8
Opened 2022-08-27 16:45 UTC by Zero2Light

2022-08-27 16:49 UTC, dujiajun requested changes

2022-08-27 16:49 UTC, dujiajun commented on oauth/views.py
> +    code = random_str(16)
用secrets模块得到密码学安全的随机数，6位就行。

2022-08-27 16:49 UTC, dujiajun commented on oauth/views.py
> +class LoginWithEmailView(APIView):
拆分成2个view，逻辑不一样的。

2022-08-27 16:49 UTC, dujiajun commented on oauth/views.py
> +            sjtu_email = re.search('.*@sjtu.edu.cn$', email)
用endswith就行了

2022-08-28 14:08 UTC, dujiajun requested changes

2022-08-28 14:08 UTC, dujiajun commented on oauth/views.py
> +    valid_time = os.environ.get('LOGIN_VERIFICATION_TIMEOUT', '')
放到settings.py中，然后这里引用settings

2022-08-28 14:08 UTC, dujiajun commented on oauth/views.py
> +    email_body = "您的登录验证码为：{0}，10分钟内有效，请尽快进行验证。".format(code)
改一下body，验证码单独成行，10分钟改成 常量/60 的形式

2022-08-28 14:08 UTC, dujiajun commented on oauth/urls.py
> +    path('login/verify/', verify_and_login, name='send_code'),
name改一下，复制粘贴没改

2022-08-28 14:08 UTC, dujiajun commented on oauth/views.py
> +def verify_and_login(request):
改成post

2022-08-28 14:08 UTC, dujiajun commented on oauth/views.py
> +def send_code(request):
用装饰器约束POST

2022-08-29 06:57 UTC, dujiajun requested changes

2022-08-29 06:57 UTC, dujiajun commented on jcourse/settings.py
> +LOGIN_VERIFICATION_TIMEOUT = int(os.environ.get('LOGIN_VERIFICATION_TIMEOUT', ''))
默认值用数字吧，单位我们统一成分钟，默认10分钟。

2022-08-29 06:57 UTC, dujiajun commented on oauth/views.py
> +    valid_minutes = math.trunc(LOGIN_VERIFICATION_TIMEOUT / 60)
和上面设置的单位一致。

2022-08-29 06:57 UTC, dujiajun commented on oauth/views.py
> +            cache.set(email, code_sent, valid_time)
改成 常量 * 60吧（确认一下cache的单位是秒？）

2022-08-29 07:03 UTC, Zero2Light commented on oauth/views.py
> +            cache.set(email, code_sent, valid_time)
嗯，是秒

2022-08-29 07:10 UTC, Zero2Light commented on oauth/views.py
> +            cache.set(email, code_sent, valid_time)
![image](https://user-images.githubusercontent.com/108635472/187143935-83bd7a9f-ed1f-4a8b-a41d-8d31dafda41d.png)

2022-08-30 16:36 UTC, dujiajun approved these changes

2022-08-30 16:37 UTC, merged